#ifndef NATURAL_DEDUCTION_H_
#define NATURAL_DEDUCTION_H_

enum class nd_step_type
{
	CONJUNCTION_INTRODUCTION,
	CONJUNCTION_ELIMINATION,
	DISJUNCTION_INTRODUCTION,
	DISJUNCTION_ELIMINATION,
	IMPLICATION_INTRODUCTION,
	IMPLICATION_ELIMINATION,
	BICONDITIONAL_INTRODUCTION,
	BICONDITIONAL_ELIMINATION,
	PROOF_BY_CONTRADICTION,
	NEGATION_ELIMINATION,

	UNIVERSAL_INTRODUCTION,
	UNIVERSAL_ELIMINATION,
	EXISTENTIAL_INTRODUCTION,
	EXISTENTIAL_ELIMINATION
};

struct nd_step {
	
};

#endif /* NATURAL_DEDUCTION_H_ */
